# Linear Algebra

In [3]:
import numpy as np

## Vectors and Matrices

### Vector

vector.shape: get dimensions of a vector 

In [4]:
x, y, z = 10, 2, 5
vector = np.array([x, y, z])
vector1 = np.array([x - 7, y, z])
vector
vector.shape

(3,)

Access

In [5]:
vector[0] # 10
vector[1] # 2

2

Operations
- Dot Product

In [6]:
np.dot(vector, vector1)

59

- Sum of vectors

In [7]:
vector + vector1
vector.reshape(3, 1)

array([[10],
       [ 2],
       [ 5]])

Module of a vector

In [8]:
np.dot(vector, vector)

129

### Matrices

In [10]:
matA = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matB = np.matrix([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
matA
matA.shape

(3, 3)

In [13]:
matA * matB

matrix([[ 42,  36,  30],
        [ 96,  81,  66],
        [150, 126, 102]])

In [29]:
matC = np.matrix([[0] * (matA.shape[0])] * (matB.shape[1]))
for r in range(matC.shape[0]):
  for c in range(matC.shape[0]):
    matC[r,c] = np.dot(matA[r,:], matB[:, c])
matC

matrix([[ 42,  36,  30],
        [ 96,  81,  66],
        [150, 126, 102]])